name: Codzienny Update Arkusza Google

on:
  schedule:
    # Uruchamia się o 7:00 UTC (czyli 9:00 czasu letniego w Polsce - CEST
    # Zimą (CET) będzie to 8:00 UTC.
    - cron: '*/10 * * * *'
  # Ten wpis pozwala na ręczne uruchomienie skryptu z panelu "Actions"
  workflow_dispatch:

jobs:
  update-google-sheet:
    runs-on: ubuntu-latest
    steps:
      # Krok 1: Pobranie kodu z repozytorium
      - name: Pobierz kod
        uses: actions/checkout@v3

      # Krok 2: Ustawienie środowiska Python
      - name: Ustaw Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Krok 3: Instalacja potrzebnych bibliotek
      - name: Zainstaluj biblioteki
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      # Krok 4: Uruchomienie skryptu
      - name: Uruchom skrypt aktualizujący
        # Tutaj przekazujemy nasz sekret do zmiennej środowiskowej
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python Slack.py