name: Daily Tweet Analysis

on:
  # Uruchamia skrypt codziennie o 7:00 UTC (9:00 czasu polskiego letniego)
  schedule:
    - cron: '0 7 * * *'

  # Pozwala na ręczne uruchomienie skryptu z poziomu zakładki "Actions" w GitHub
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobranie kodu z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Krok 2: Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Krok 3: Instalacja zależności z pliku requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas 
          pip install openai
          pip install gspread
          

      # Krok 4: Uruchomienie skryptu analizy
      - name: Run Python script
        env:
          # Przekazanie sekretów do środowiska skryptu
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GCP_SA_KEY }}
        run: python TEST.py